const express = require('express')
const app = express()
const server = require('http').Server(app)
const io = require('socket.io')(server)
const { v4: uuidV4 } = require('uuid')
const accountSid = 'AC08cd9d05bafa28d53b18c51a99c239c1';
const authToken = '44cff501ad82c480c7685e1c8f528f6b';
let ice;



app.get('/abcd', (req, res) => {
  res.json({
    "fusion": {
        "facet_labels": [
            "cities_ss:cities_ss,cuisine:cuisine,cities_state_ss:cities_state_ss"
        ]
    },
    "response": {
        "docs": [
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Aloft Atlanta Downtown",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.38962,
                "property_code": "ALFT",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLDN/atldn-wxyz-5790-hor-feat.jpg?download=2880px:*",
                "phone_area_city_code": "678",
                "restaurant_url": "missing",
                "brand_name": "Aloft",
                "name": "WXYZ Bar",
                "phone_number": "515-0300",
                "breakfast": true,
                "brand_code": "ALFT",
                "latitude": 33.76253,
                "description": "End all of your evenings at our hotel bar, where you can mix and mingle in a trendy setting. After an action-packed day at Georgia Aquarium, socialize with friends over signature craft cocktails, hot and cold appetizers and tasty bar bites.\n",
                "reservation_required": false,
                "address_line_1": "300 Ted Turner Drive NW",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atldn-aloft-atlanta-downtown/",
                "phone_country_code": "1",
                "cuisine": "Bar",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167321",
                "geodist()": 1.8830535,
                "score": 1.9981205
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "GLENN HOTEL, AUTOGRAPH COLLECTION",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.39303,
                "property_code": "GLN",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLAK/atlak-kitchen-0050-hor-feat.jpg?download=2880px:*",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Glenn",
                "name": "Glenn's Kitchen",
                "phone_number": "521-2250",
                "breakfast": true,
                "brand_code": "GLN",
                "latitude": 33.757,
                "description": "Southern comfort food with a twist is on the menu at Glenn's Kitchen, our on-site restaurant. Dining options include cornmeal crusted trout, fried Georgia chicken and shrimp and grits; stop by for a meal and a cocktail after a busy afternoon in Atlanta.\n",
                "reservation_required": false,
                "address_line_1": "110 Marietta St. NW",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atlak-glenn-hotel-autograph-collection/",
                "phone_country_code": "1",
                "cuisine": "American",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167320",
                "geodist()": 1.7324878,
                "score": 1.9982705
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Sheraton Atlanta",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.38324,
                "property_code": "SHR",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLXS/atlxs-bar-9712-hor-feat.jpg?download=2880px:*",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Sheraton",
                "name": "Collage Restaurant",
                "phone_number": "659-6500",
                "breakfast": true,
                "brand_code": "SH",
                "latitude": 33.75898,
                "description": "Collage Restaurant boasts thoughtful placement in the heart of our downtown Atlanta hotel featuring casual breakfast options and creative lunch menus. Get energized for the day ahead with our breakfast buffet, or choose from seasonal á la carte options.\n",
                "reservation_required": false,
                "address_line_1": "165 Courtland Street NE",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atlxs-sheraton-atlanta-hotel/",
                "phone_country_code": "1",
                "cuisine": "Continental",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167322",
                "geodist()": 2.2637875,
                "score": 1.9977413
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Westin Atlanta",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.387917,
                "property_code": "WS",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLPL/atlpl-bar-0783-hor-clsc.jpg?downsize=1160px:*",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Westin",
                "name": "Bar 210",
                "phone_number": "589-7506",
                "breakfast": true,
                "brand_code": "WS",
                "latitude": 33.759411,
                "description": "Catch up with family and friends after a busy day of touring Atlanta in our inviting hotel bar. Enjoy a light meal before heading out for an evening downtown or meet for one last nightcap before heading to your relaxing room. Bar 210 is temporarily closed\n",
                "reservation_required": false,
                "address_line_1": "210 Peachtree St. NW",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atlpl-the-westin-peachtree-plaza-atlanta/",
                "phone_country_code": "1",
                "cuisine": "Bar",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167324",
                "geodist()": 1.994024,
                "score": 1.9980099
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "GLENN HOTEL, AUTOGRAPH COLLECTION",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.39303,
                "property_code": "GLN",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLAK/atlak-kitchen-0050-hor-feat.jpg?download=2880px:*",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Glenn",
                "name": "Ruth's Chris Steak House",
                "phone_number": "223-6500",
                "breakfast": true,
                "brand_code": "GLN",
                "latitude": 33.757,
                "description": "Ruth's Chris Steak House is a family of 75 fine dining restaurants that originated in New Orleans. Serves: U.S.D.A. prime beef and other premium cuts, Louisiana Seafood Gumbo, Barbecued Shrimp, French Fried Onion Rings, Smoked Salmon, Blackened Tuna.\n",
                "reservation_required": false,
                "address_line_1": "110 Marietta St. NW",
                "on_property": "Nearby",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atlak-glenn-hotel-autograph-collection/",
                "phone_country_code": "1",
                "cuisine": "American",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167319",
                "geodist()": 1.7324878,
                "score": 1.9982705
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Westin Atlanta",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.387917,
                "property_code": "WS",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLPL/atlpl-cafe-1773-hor-clsc.jpg?downsize=1160px:*",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Westin",
                "name": "The Café",
                "phone_number": "589-7506",
                "breakfast": true,
                "brand_code": "WS",
                "latitude": 33.759411,
                "description": "Kick off your busy day in Atlanta with a Southern-style buffet breakfast in our lobby restaurant.",
                "reservation_required": false,
                "address_line_1": "210 Peachtree St. NW",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atlpl-the-westin-peachtree-plaza-atlanta/",
                "phone_country_code": "1",
                "cuisine": "American",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167325",
                "geodist()": 1.994024,
                "score": 1.9980099
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Ritz Carlton",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.38715,
                "property_code": "RTC",
                "image_url": "https://s7d2.scene7.com/is/image/ritzcarlton/RCATLAN_00392?$LargeViewport42pct$",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Ritz Carlton",
                "name": "Lumen Bar",
                "phone_number": "5952 3333",
                "breakfast": true,
                "brand_code": "RC",
                "latitude": 33.75858,
                "description": "Decadent lighting and elegant furnishings create the ideal nightlife destination. Signature cocktails and flavorful cuisine are offered nightly, and live music is featured on select evenings.",
                "reservation_required": false,
                "address_line_1": "181 Peachtree Street, N.E.",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.ritzcarlton.com/en/hotels/georgia/atlanta",
                "phone_country_code": "1",
                "cuisine": "Bar",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167328",
                "geodist()": 2.044714,
                "score": 1.9979594
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Atlanta Marriott Marquis",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.38496,
                "property_code": "AMM",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/EB/eb-dining-0001-hor-clsc.jpg",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Courtyard By Marriott",
                "name": "MoMo Café",
                "phone_number": "3991 6499",
                "breakfast": true,
                "brand_code": "CY",
                "latitude": 33.76158,
                "description": "Featuring lunch and dinner, as well as an extensive a la carte menu, this restaurant offers the best in international casual dining in Jiading District.",
                "reservation_required": false,
                "address_line_1": "265 Peachtree Center Avenue",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atlmq-atlanta-marriott-marquis/",
                "phone_country_code": "1",
                "cuisine": "International",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167317",
                "geodist()": 2.151884,
                "score": 1.9978528
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "COURTYARD ATLANTA DOWNTOWN",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.426838,
                "property_code": "CY",
                "image_url": "https://cache.marriott.com/marriottassets/marriott/ATLDO/atldo-bistro-1838-hor-feat.jpg?download=2880px:*",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Courtyard By Marriott",
                "name": "The Bistro - Eat. Drink. Connect.®",
                "phone_number": "222-2416",
                "breakfast": true,
                "brand_code": "CY",
                "latitude": 33.67973,
                "description": "A popular food and beverage destination awaits at our hotel restaurant in downtown Atlanta. The Bistro offers refreshing breakfast choices and a variety of dinner and cocktail options, as well as specialty beverages made with Starbucks® coffee.\n",
                "reservation_required": false,
                "address_line_1": "133 Carnegie Wa",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.marriott.com/hotels/travel/atldo-courtyard-atlanta-downtown/",
                "phone_country_code": "1",
                "cuisine": "American",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167318",
                "geodist()": 5.73843,
                "score": 1.9942944
            },
            {
                "country": "USA",
                "lunch": true,
                "property_name": "Ritz Carlton",
                "property_service_level": "Full Service",
                "state": "GA",
                "longitude": -84.38715,
                "property_code": "RTC",
                "image_url": "https://s7d2.scene7.com/is/image/ritzcarlton/RCATLAN_00392?$LargeViewport42pct$",
                "phone_area_city_code": "404",
                "restaurant_url": "missing",
                "brand_name": "Ritz Carlton",
                "name": "AG",
                "phone_number": "5952 3333",
                "breakfast": true,
                "brand_code": "RC",
                "latitude": 33.75858,
                "description": "The menu at this modern bar and steakhouse focuses on simple flavors, regional growers and seasonal ingredients. Delight in chef creations featuring fresh, southern-inspired fare during the weekends.\n",
                "reservation_required": false,
                "address_line_1": "181 Peachtree Street, N.E.",
                "on_property": "Yes",
                "email": "missing",
                "hotel_website_url": "https://www.ritzcarlton.com/en/hotels/georgia/atlanta",
                "phone_country_code": "1",
                "cuisine": "American",
                "dinner": true,
                "address_city": "Atlanta",
                "operating_hours": "06:00 - 22:30 (Mon-Sun)",
                "id": "5167327",
                "geodist()": 2.044714,
                "score": 1.9979594
            }
        ],
        "numFound": 12,
        "start": 0,
        "maxScore": 1.9982705,
        "numFoundExact": true
    },
    "responseHeader": {
        "zkConnected": true,
        "QTime": 7,
        "totalTime": 41,
        "params": {
            "pt": "33.7627,-84.4224",
            "bf": "recip(geodist(),1,1000,1000)",
            "fl": [
                "property_code",
                "property_name",
                "id",
                "brand_code",
                "brand_name",
                "name",
                "id",
                "cuisine",
                "description",
                "on_property",
                "phone_country_code",
                "phone_area_city_code",
                "phone_number",
                "latitude",
                "longitude",
                "property_service_level",
                "hotel_website_url",
                "image_url",
                "address_line_1",
                "address_city",
                "state",
                "country",
                "email",
                "attire",
                "breakfast",
                "lunch",
                "dinner",
                "operating_hours",
                "reservation_required",
                "restaurant_url",
                "score",
                "geodist()"
            ],
            "f.cuisine.facet.mincount": "1",
            "cuisine:(\"Continental\" OR \"American\" OR \"Bar\")": "",
            "fq": "{!bbox sfield= location_srptm}",
            "_forwardedCount": "1",
            "f.cities_state_ss.facet.mincount": "0",
            "uf": "_query_ *",
            "defType": "edismax",
            "shards.preference": "replica.type:PULL",
            "facet.field": "{!ex=\"cuisine\"}cuisine",
            "d": "30",
            "lw.pipelineId": "restaurant",
            "start": "0",
            "isFusionQuery": "true",
            "sort": "stars desc",
            "rows": "10",
            "sfield": "location_srptm",
            "queryProfileID": "restaurants",
            "fusionQueryId": "DBxzMnYXN3",
            "f.cities_ss.facet.mincount": "1",
            "q": "*:*",
            "distanceUnits": "miles",
            "facet": "true"
        },
        "status": 0
    },
    "facet_counts": {
        "facet_queries": {},
        "facet_fields": {
            "cuisine": [
                "American",
                6,
                "Bar",
                4,
                "Continental",
                1,
                "International",
                1
            ]
        },
        "facet_ranges": {},
        "facet_intervals": {},
        "facet_heatmaps": {}
    }
})
})


server.listen(process.env.PORT || 3000,function(){
  console.log('listening at 3000');
});